### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MidimasterSoft** [bmx-ng/image.mod#12]
UPPS... already done....

If you now add animated GIF to BlitzMax NG... Wouldn't it be the best time to also integrate the GIF's "individual-Delay-on-each-frame" feature as a new property (field) into TImage?

Each Gif-frame has a Delay:BYTE in the header of each frame, that tells me how long this frames should be displayed in 1/100sec. So if you add an Field Delay:Int[n] to type TImage the user can aks for the display time of each image-frame.

This enables to "play" animated GIFs in their original timing

**Comment by woollybah** [comment]
We are storing them in milliseconds, since it makes more sense in the context of everything else being in milliseconds.

**Comment by woollybah** [comment]
`example_02.bmx` demonstrates the use of the delay.

**Comment by MidimasterSoft** [comment]
good job... I recognized the feature after I had written the issue report. So I closed it immediately
