### ISSUE TITLE
PNG issue

### ISSUE THREAD

**Issue by thareh** [bmx-ng/image.mod#17]
Hey,

Loading this png does not seem to function properly, the pixmap is all empty.

```
Framework BRL.Blitz
Import Image.PNG

Local pixmap:TPixmap = LoadPixmap("in.png")
Assert pixmap, "Unable to load pixmap"

SavePixmapPNG(pixmap, "out.png")
```

[in.png](https://public.thareh.se/blitzmax/in.png)

Thanks!

**Comment by GWRon** [comment]
That PNG is grayscale. and during loading it is converted

```
Framework BRL.Blitz
Import Image.PNG
Import Brl.StandardIO

Local pixmap:TPixmap = LoadPixmap("in.png")
rem
Const PF_I8=				1
Const PF_A8=				2
Const PF_BGR888=			3
Const PF_RGB888=			4
Const PF_BGRA8888=  		5
Const PF_RGBA8888=  		6
endrem
print pixmap.format  'prints 6, so converted to RGBA8888

SavePixmapPNG(pixmap, "out.png")
```

I assume during loading the grayscale information is transformed RGB ... but they missed the alpha channel.

To verify that: Open up the image in GIMP and use the color picker on the "transparent" pixels ... color will change.

Load it in krita and check the "channels" - the content is still there, just alpha is missing (all set to "0% opaque"):
![image](https://user-images.githubusercontent.com/2625226/215287951-ae245b6e-9b3c-46a0-967b-48a657dd31b1.png)

**Comment by GWRon** [comment]
Loading it will go this path there:
mods/image.mod/png.mod/png.bmx
```
Function LoadPixmapPNG:TPixmap( url:Object )
...
			Case PNG_COLOR_TYPE_GRAY_ALPHA
				pixmap=CreatePixmap( width,height,PF_RGBA8888 )
				Local rows:Byte Ptr Ptr=png_get_rows( png_ptr,info_ptr )
				For Local y:Int=0 Until height
					Local src:Byte Ptr=rows[y]
					Local dst:Byte Ptr=pixmap.PixelPtr(0,y)
					For Local x:Int=0 Until width
						Local a:Int=src[0]
						Local i:Int=src[1]
						dst[0]=i
						dst[1]=i
						dst[2]=i
						dst[3]=a
						src:+2
						dst:+4
					Next
				Next
			End Select
```

As our goal here is to always get a "RGBA8888" - this is from the libpng docs:
```
For some uses, you may want a grayscale image to be represented as RGB. This code will do that conversion:

    if (color_type == PNG_COLOR_TYPE_GRAY ||
        color_type == PNG_COLOR_TYPE_GRAY_ALPHA)
          png_set_gray_to_rgb(png_ptr);
```

**Comment by GWRon** [comment]
In the function above: I switched
```
						Local a:Int=src[0]
						Local i:Int=src[1]
```
with
```
						Local a:Int=src[0]
						Local i:Int=src[1]
```
And the output looks as desired.

PNG_COLOR_TYPE_GRAY_ALPHA
- naming scheme mentions "gray" before "alpha"

**Comment by GWRon** [comment]
Pay attention to the implicit conversion of the "gray_alpha" into "RGBA888".
So the saved PNG has now three channels (rgb + a) instead of 2 (i + a).

**Comment by thareh** [comment]
Ah, awesome! Thanks you for looking into it!

**Comment by GWRon** [comment]
@woollybah did you have to change something in the libpng (after updating it) ? the changes-file does not mention something regarding colors or "gray alpha" pngs. Code changes contain that `png_set_gray_to_rgb` -- so maybe they did not know they "accidentally" fixed that issue (which nobody reported :D)
